source ~/.profile

if [[ -z $DISPLAY && $(tty) == /dev/tty1 ]]; then
        startx -- -nocursor
fi

alias ll="ls -la"
alias python="python3"
alias pip="pip3"
alias PSPORT="netstat -tulpn | grep :"
alias PS="ps -ef | grep -i"

alias flaskup="export FLASK_APP=proxy.py && cd $GOPATH/src/github.com/byu-oit/av-scheduling-exchange-microservice/ && flask run --host=0.0.0.0 &"

xset -display :0 dpms force on

cd ~/go/src/github.com/byu-oit/av-scheduling-ui
